config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles, only: [:create, :new, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
  <div class="main-content">
    <% @articles.all.each do |article| %>
      <%= link_to article_path(article) do %>
        <div class="article-preview">
          <h2 class="preview-title"><%= article.title %></h2>
          <p class="preview-description"></p><%= article.description %></p>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/articles/new.html.erb
<div class="container">
  <div class="header d-flex justify-content-between">
    <div class="page-title">
      <h1>New post</h1>
      <p class="subtitle">You can post anything you want in here.</p>
      <p class="subtitle">I might delete it.</p>
    </div>
    <div class="flex-item">
      <%= link_to 'Go back', root_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <div class="main-content">
    <%= simple_form_for @article do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :content %>
      <%= f.submit class: 'btn btn-outline-success'%>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="header d-flex justify-content-between">
    <div class="page-title">
      <h1><%= @article.title %></h1>
    </div>
    <div class="flex-item">
      <%= link_to 'Go back', root_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <div class="main-content">
    <%= @article.content %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeej</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= link_to '+ Post', new_article_path, class: "btn btn-outline-secondary new-post" %>
<%= link_to root_path, class: "navbar" do %>
<div class="container">
  <div class="navbar-title">
    <h1>Jeej articles</h1>
  </div>
  <div class="navbar-description">
    <p>You can write anything you want in here</p>
    <p>I might delete it.</p>
  </div>
</div>
<% end %>